### ISSUE TITLE
realm not found

### ISSUE THREAD

**Issue by MInus63** [PierreGode/Linux-Active-Directory-join-script#30]
Hello

I used your script to integrate one of my debian10 VM in active directory.
But after a few months of use and a migration of the VM from HyperV to Esxi I have a bad surprise:
In the VM when I type id "username" of a user who is already connected to the server, the VM finds without problem the UID and GID of username.
But when I do the same search for someone who has never connected, the server returns: id: "username" : non-existent user !!
if I use the search error function of your script this is what I get back:

`Realm not found`

But if i use realm discover domain.lan the answer is:
```
domain.lan
  type: kerberos
  realm-name: DOMAIN.LAN
  domain-name: domain.lan
  configured: kerberos-member
  server-software: active-directory
  client-software: sssd
  required-package: sssd-tools
  required-package: sssd
  required-package: libnss-sss
  required-package: libpam-sss
  required-package: adcli
  required-package: samba-common-bin
  login-formats: %U
  login-policy: allow-permitted-logins
  permitted-logins:
  permitted-groups:
```
I said to myself that there was a problem of connection with the domain and that the solution is to leave the domain and come back, but when I use this function 5 of your script here is the answer:

```
realm: No default realm discovered
realm: No default realm discovered
Realm not found, nothing to leave
```

If i want to reauthenticate (fonction 4) thos is the answer

```
Rejoin to AD
find: ‘/home/domain.lan’: Aucun fichier ou dossier de ce type
realm: No default realm discovered
realm: No default realm discovered
Do you really want to leave the domain:  (y/n)?n
Bye
```
I know I don't use the normalized path /home/domain.lan, but my users ask me for it.

Do you have a solution to re-authenticate?

in advance, thank you very much for your help.
